language: c
os: osx
xcode: xcode9.4

script:
- mkdir /tmp/libdispatch.dst
- xcodebuild -project libdispatch.xcodeproj -target libdispatch DSTROOT=/tmp/libdispatch.dst CODE_SIGN_IDENTITY=""
- xcodebuild -project libdispatch.xcodeproj -target libsystem_blocks DSTROOT=/tmp/libdispatch.dst CODE_SIGN_IDENTITY=""
